// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://injufsjwkecdhfookfxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluanVmc2p3a2VjZGhmb29rZnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MDkzNzYsImV4cCI6MjA1MzQ4NTM3Nn0.MgefeywHfws-ke1SZrHBWOPJH9CzPIdj4Z_2WsHiEbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);